network:
  amb:
    http-url: http://127.0.0.1:8545
    ws-url: ws://127.0.0.1:8546
    contract-addr: 'will be set by deploy script'
    vs-contract-addr: '0x0000000000000000000000000000000000000F00'
  eth:
    http-url: http://127.0.0.1:8502
    ws-url: ws://127.0.0.1:3434
    contract-addr: 'will be set by deploy script'
    epoch-length: 3
external-logger:
  telegram:
    token: null
    chat-id: null
prometheus:
  ip: localhost
  port: 9091
