network:
  amb:
    url: wss://network.ambrosus-dev.io
    contract-addr:
    vs-contract-addr:
  eth:
    url: wss://rinkeby.infura.io/ws/v3/01117e8ede8e4f36801a6a838b24f36c
    contract-addr:
    ethash-path: ./todo

external-logger:
  telegram:
    token:
    chat-id:
