@startuml

actor Frontend
participant AmbBridgeContract
participant Relay
participant EthBridgeContract


...
...


Frontend -> AmbBridgeContract : withdraw
note right: same timeframe
AmbBridgeContract -> AmbBridgeContract: add withdraw to queue
AmbBridgeContract ->: Event `Withdraw`
-> Frontend: 1.1

...

Frontend -> AmbBridgeContract : withdraw
note right: new timeframe

AmbBridgeContract ->: Event `Transfer`
-> Frontend: 2.1

Relay -> Relay : Wait next 10 blocks (safety blocks)
-> Frontend: 2.2
...

Relay -> EthBridgeContract : submitTransfers
EthBridgeContract -> EthBridgeContract: lock transfers on N seconds
EthBridgeContract ->: Event `TransferSubmit`
-> Frontend: 3.1
...

Relay -> EthBridgeContract: unlockTransfers
EthBridgeContract ->: call erc20 contracts\n to transfer tokens
EthBridgeContract ->: Event `TransferFinish`
-> Frontend: 3.2


@enduml

