name: default

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  ts-test:
    name: Type Script Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - name: Install Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.3

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

  go-tests:
    name: Golang Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./relay
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get ./...

      - name: Unit Tests
        run: go test --short ./... -tags ci
