name: default

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  go-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./relay
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Unit Tests
        run: go test --short ./...
