name: Publish a docker image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'aura_finalizing_service/**'


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta_finalizing
        with:
          images: ghcr.io/ambrosus/ambrosus-finalizing

      - uses: docker/build-push-action@v3
        with:
          context: ./aura_finalizing_service
          push: true
          tags: ${{ steps.meta_relay.outputs.tags }}
          labels: ${{ steps.meta_relay.outputs.labels }}
